name = "isso-subdomain-worker"
main = "worker.js"
compatibility_date = "2024-09-01"

routes = [
  { pattern = "*.isso.gay/*", zone_name = "isso.gay" }
]

# Fill this with your Cloudflare account ID:
account_id = "a09c79f59b964b75b2fa658f8a244fea"

[vars]
# Firebase Hosting origin (can be your custom apex domain once validated)
ORIGIN = "https://isso.gay"
